name: Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gradle:
    runs-on: windows-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v1
    
      - name: setup JDK8 version
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run gradle clean and build
        run: ./gradlew clean build

      - name: run gradle detekt
        run: ./gradlew detekt
          
      - name: build desktop snapshot jar
        run: ./gradlew shadowJar
