name: Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gradle:
    runs-on: windows-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v1
    
      - name: setup JDK8 version
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: run gradle clean and build
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: gradle/wrapper
          arguments: clean build

      - name: run gradle detekt
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: gradle/wrapper
          arguments: detekt
          
      - name: build desktop snapshot jar
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: gradle/wrapper
          arguments: shadowJar
